[LOGICALS]
IDFTITLE = Events Demo
APIKEY = <Google API Key>

#file .\asn\emailsettings.asn


[SETTINGS]
$enhanced_edit    = all 
;$SEARCH_OBJECT    = dbms_first
$variation        = SYSTEM_LIBRARY
$RESOURCES_OUTPUT = .\bin
$SEARCH_RESOURCES = resources_last 
$Symbol_Table     = 2
$putmess_logfile  =.\log\%t_wasv%p.log 
$search_skeleton  = external_first
$TEST_MODE_COMPONENTS 
$SEARCH_SKELETON = external_first
;$ioprint = 511

;$proc_tracing = true
;$PROC_LOG_FILE = .\log\profiling.log
;$proc_tracing_addition = "%%$datim - %%$componentname - Status: %%$status "


[web]
;;$UNIFACE_RUNTIME_BASE_URL = /uniface/common
$JS_BASE_URL = ../dspjs/

[RESOURCES]
.\bin
usys:uidf.uar

[FILES]
usys:idf.aps            usysuniface:components\idf.aps
usys:uu*.frm            usysuniface:components\uu*.frm
usys:uu*.svc            usysuniface:components\uu*.svc
common:uu*.frm          usys:..\components\uu*.frm
common:uu*.svc          usys:..\components\uu*.svc
common:ur*.svc          usys:..\components\ur*.svc
usys:*.xml              usysuniface:misc\*.xml
 
*.hts			skeleton\*.hts

[PROXY_SETTINGS]
$BYPASS = *


[DRIVER_SETTINGS]
SLE     U1.0
MSS	U5.0
PGS     U1.0 
USYS$SLE_PARAMS create db = on, identifiers = quoted 
USYS$MSS_PARAMS = hs:on, ids:quoted, procs:off,locktime:360, keysetcursor:on,checks:off
USYS$PGS_PARAMS identifiers = unquoted, procedures : off,  segmented fields : off, blobs : on

[PATHS]
$MSS	MSS:PAPERROUTE:PAPERROUTE||
$PGS	PGS:PostgreSQL35W:public|events|uniface

; Path to the SQLite database for the Uniface Repository:
$DBMS        SLE:.\dbms\usys.db
; Path to the SQLite database for User defined data:
$DBMS_DEF    SLE:.\dbms\userdata.db

$SYS    $DBMS
$UUU    $DBMS
$IDF    $DBMS

$DEF    $DBMS_DEF
;$DEF	$PGS


[ENTITIES] 
*.PGS = $PGS:pg_catalog.*.*
;*.EVENTS = $PGS:*.*


[USER_3GL] 